repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    # Identify invalid files
    - id: check-yaml
    - id: check-json

    # git checks
    - id: check-merge-conflict
    - id: check-added-large-files
    - id: check-case-conflict
    - id: forbid-new-submodules

    # Security
    - id: detect-aws-credentials
      args:
        - --allow-missing-credentials
    - id: detect-private-key

    # General quality checks
    - id: mixed-line-ending
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-executables-have-shebangs
    - id: end-of-file-fixer

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.0
    hooks:
    - id: check-github-actions
    - id: check-github-workflows

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.5 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
    - id: markdownlint
      args: [--fix]
